### ISSUE TITLE
invalid data path in supersid.cfg

### ISSUE THREAD

**Issue by kunkleb** [sberl/supersid#32]
A more complete data path is required in supersid.cfg
Currently data_path = /tmp/Data
Should be data_path = /home/pi/tmp/Data

**Comment by fenrog** [comment]
`/home/pi/tmp/Data` works only for the standard Raspberry pi installation when the user doesn't use his own user name.

The data_path in supersid.cfg was `/tmp/Data`. Since November 12 it is `../Data`.
I intentionally used a path relative to the script folder. This setting works for Windows and Linux.

What is the benefit of the proposed change?

**Comment by kunkleb** [comment]
The supersid.cfg with ../Data works fine now.  The original supersid.cfg
gave me an invalid path error.
I believe this issue should now be closed.
